-- A shared bank of exam-style practice questions, keyed to the syllabus
-- catalogue (webapp/src/lib/syllabus) by spec and topic.
--
-- Why a bank at all: every practice question so far was generated by the AI
-- on demand, so a new student, a student out of AI allowance or an AI outage
-- meant no practice. Bank questions work on day one and cost nothing per use.
--
-- Where questions come from (see docs/QUESTION_SOURCES.md):
--   'learnora' — written for Learnora against each spec section.
--   'oak'      — Oak National Academy lesson quizzes, Open Government Licence
--                v3.0, imported by scripts/question-bank/import-oak.mjs.
-- Exam-board past papers are NOT stored here: AQA, OCR, Pearson and the IB
-- all reserve them, and AQA refuses permission for apps.
--
-- Every row carries its licence and the attribution to show beside it.
--
-- Access: reference data, the same for everyone. Any signed-in student may
-- read it; nobody but the service role (the importer) may write. RLS has a
-- select policy only, and write privileges are revoked as well, so a missing
-- policy can never become an open door.
--
-- spec_key is the spec's question-bank key: the spec id, except for specs
-- that share content (the three GCSE Maths specs all use 'gcse-maths').
--
-- Revert: drop table if exists public.question_bank;

create table if not exists public.question_bank (
  id            uuid primary key default gen_random_uuid(),
  source        text not null check (source in ('learnora', 'oak')),
  source_ref    text check (source_ref is null or char_length(source_ref) <= 200),
  licence       text not null check (licence in ('learnora', 'OGL-3.0')),
  attribution   text check (attribution is null or char_length(attribution) <= 300),
  spec_key      text not null check (spec_key ~ '^[a-z0-9-]{3,60}$'),
  topic_ref     text not null check (char_length(topic_ref) between 1 and 20),
  -- null: examined at every tier of the spec
  tier          text check (tier is null or tier in ('Foundation', 'Higher', 'SL', 'HL')),
  question      text not null check (char_length(question) between 5 and 1000),
  choices       jsonb not null check (
                  jsonb_typeof(choices) = 'array'
                  and jsonb_array_length(choices) between 2 and 6
                ),
  correct_index smallint not null check (correct_index between 0 and 5),
  explanation   text check (explanation is null or char_length(explanation) <= 1000),
  -- sha-256 of the normalised question and choices; re-imports are no-ops
  content_hash  text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  created_at    timestamptz not null default now(),
  unique (source, content_hash),
  check (correct_index < jsonb_array_length(choices))
);

create index if not exists question_bank_spec_topic_idx
  on public.question_bank (spec_key, topic_ref);

alter table public.question_bank enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'question_bank'
      and policyname = 'question_bank_read_signed_in'
  ) then
    create policy "question_bank_read_signed_in" on public.question_bank
      for select to authenticated using (true);
  end if;
end $$;

revoke insert, update, delete, truncate on public.question_bank from anon, authenticated;
revoke select on public.question_bank from anon;
