-- Baseline: the tables that were created by hand in the Supabase dashboard
-- before this repo kept migrations. Every later migration alters them, so a
-- fresh database (local dev, CI, a new project) cannot be built without this.
--
-- RECONSTRUCTED from the app code (webapp/src/api/types.ts, the api/*
-- modules) and from the policy and constraint names later migrations refer
-- to — not dumped from production. Columns that a later migration adds are
-- deliberately left out so those migrations still run as written.
--
-- Safe on production: every statement is `if not exists` or guarded, so
-- applying it to a database that already has these tables changes nothing.

-- Legacy profiles table. 20260727000000 alters its policy and 20260729121611
-- drops it; 20260803000000 creates the real one.
do $$
begin
  if to_regclass('public.profiles') is null
     and not exists (
       select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relname = 'friendships'
     ) then
    create table public.profiles (
      id uuid primary key references auth.users (id) on delete cascade,
      dob date
    );
    alter table public.profiles enable row level security;
    create policy "Users can manage own profile" on public.profiles
      for all using (auth.uid() = id);
  end if;
end $$;

create table if not exists public.folders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  name text not null,
  color text not null default '#6366f1',
  created_at timestamptz not null default now()
);

create table if not exists public.materials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  folder_id uuid,
  title text not null,
  type text not null default 'text',
  raw_content text,
  storage_path text,
  created_at timestamptz not null default now(),
  constraint materials_folder_id_fkey
    foreign key (folder_id) references public.folders (id) on delete set null
);

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  material_id uuid references public.materials (id) on delete cascade,
  markdown_content text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.flashcard_decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  folder_id uuid,
  title text not null,
  created_at timestamptz not null default now(),
  constraint flashcard_decks_folder_id_fkey
    foreign key (folder_id) references public.folders (id) on delete set null
);

create table if not exists public.flashcards (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete cascade,
  deck_id uuid references public.flashcard_decks (id) on delete cascade,
  front text not null,
  back text not null,
  next_review_date date,
  srs_interval integer not null default 0,
  ease_factor real not null default 2.5,
  created_at timestamptz not null default now()
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  exam_name text not null,
  exam_date date not null,
  difficulty text,
  status text
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  text text not null,
  is_done boolean not null default false
);

-- The four tables from supabase_new_tables.sql (run in the SQL editor, never
-- as a migration).
create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  task text,
  folder_id uuid references public.folders (id) on delete set null,
  minutes int not null check (minutes >= 1),
  timer_type text,
  started_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists study_sessions_user_started_idx
  on public.study_sessions (user_id, started_at desc);

create table if not exists public.weekly_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  week_start date not null,
  plan_json jsonb not null,
  source text not null default 'ai',
  created_at timestamptz not null default now(),
  unique (user_id, week_start)
);

create table if not exists public.quizzes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  material_id uuid references public.materials (id) on delete set null,
  folder_id uuid,
  title text not null,
  questions_json jsonb not null,
  created_at timestamptz not null default now(),
  constraint quizzes_folder_id_fkey
    foreign key (folder_id) references public.folders (id) on delete set null
);

create table if not exists public.quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  quiz_id uuid not null references public.quizzes (id) on delete cascade,
  score int not null,
  total int not null,
  answers_json jsonb not null,
  weak_topics text[],
  created_at timestamptz not null default now()
);
create index if not exists quiz_attempts_user_created_idx
  on public.quiz_attempts (user_id, created_at desc);

-- RLS and the policy names later migrations `alter policy` by name.
do $$
declare
  p record;
begin
  for p in
    select * from (values
      ('exams', 'Select own exams', 'select', 'auth.uid() = user_id', null),
      ('exams', 'Insert own exams', 'insert', null, 'auth.uid() = user_id'),
      ('exams', 'Update own exams', 'update', 'auth.uid() = user_id', 'auth.uid() = user_id'),
      ('exams', 'Delete own exams', 'delete', 'auth.uid() = user_id', null),
      ('tasks', 'Select own tasks', 'select', 'auth.uid() = user_id', null),
      ('tasks', 'Insert own tasks', 'insert', null, 'auth.uid() = user_id'),
      ('tasks', 'Update own tasks', 'update', 'auth.uid() = user_id', 'auth.uid() = user_id'),
      ('tasks', 'Delete own tasks', 'delete', 'auth.uid() = user_id', null),
      ('folders', 'Users can manage their own folders', 'all', 'auth.uid() = user_id', null),
      ('materials', 'Users can manage their own materials', 'all', 'auth.uid() = user_id', null),
      ('notes', 'Users can manage their own notes', 'all', 'auth.uid() = user_id', null),
      ('flashcard_decks', 'Users can manage their own decks', 'all', 'auth.uid() = user_id', null),
      ('flashcards', 'Users can manage their own flashcards', 'all', 'auth.uid() = user_id', null),
      ('study_sessions', 'study_sessions_select_own', 'select', 'auth.uid() = user_id', null),
      ('study_sessions', 'study_sessions_insert_own', 'insert', null, 'auth.uid() = user_id'),
      ('study_sessions', 'study_sessions_delete_own', 'delete', 'auth.uid() = user_id', null),
      ('weekly_plans', 'weekly_plans_select_own', 'select', 'auth.uid() = user_id', null),
      ('weekly_plans', 'weekly_plans_upsert_own', 'insert', null, 'auth.uid() = user_id'),
      ('weekly_plans', 'weekly_plans_update_own', 'update', 'auth.uid() = user_id', 'auth.uid() = user_id'),
      ('weekly_plans', 'weekly_plans_delete_own', 'delete', 'auth.uid() = user_id', null),
      ('quizzes', 'quizzes_select_own', 'select', 'auth.uid() = user_id', null),
      ('quizzes', 'quizzes_insert_own', 'insert', null, 'auth.uid() = user_id'),
      ('quizzes', 'quizzes_delete_own', 'delete', 'auth.uid() = user_id', null),
      ('quiz_attempts', 'quiz_attempts_select_own', 'select', 'auth.uid() = user_id', null),
      ('quiz_attempts', 'quiz_attempts_insert_own', 'insert', null, 'auth.uid() = user_id'),
      ('quiz_attempts', 'quiz_attempts_delete_own', 'delete', 'auth.uid() = user_id', null)
    ) as t(tbl, name, cmd, using_expr, check_expr)
  loop
    execute format('alter table public.%I enable row level security', p.tbl);
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public' and tablename = p.tbl and policyname = p.name
    ) then
      execute format(
        'create policy %I on public.%I for %s to authenticated%s%s',
        p.name, p.tbl, p.cmd,
        case when p.using_expr is null then '' else ' using (' || p.using_expr || ')' end,
        case when p.check_expr is null then '' else ' with check (' || p.check_expr || ')' end
      );
    end if;
  end loop;
end $$;

-- Grants the dashboard gave these tables implicitly. Without them the Data API
-- cannot reach them now that new tables are not auto-exposed.
grant select, insert, update, delete on
  public.folders, public.materials, public.notes, public.flashcard_decks,
  public.flashcards, public.exams, public.tasks, public.study_sessions,
  public.weekly_plans, public.quizzes, public.quiz_attempts
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;
